/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_e3557d40 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/pltxfytwmrkmowxdnuow/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";
import type { JsonValue } from "./types.ts";

let _client: ReturnType<typeof createClient> | null = null;
const client = () => {
  if (!_client) {
    _client = createClient(
      Deno.env.get("SUPABASE_URL"),
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || Deno.env.get("SERVICE_ROLE_KEY"),
    );
  }
  return _client;
};

type KVEntry<T extends JsonValue = JsonValue> = { key: string; value: T };

// Set stores a key-value pair in the database.
export const set = async <T extends JsonValue>(key: string, value: T): Promise<void> => {
  const supabase = client();
  const { error } = await supabase.from("kv_store_e3557d40").upsert({
    key,
    value,
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async <T extends JsonValue>(key: string): Promise<T | null> => {
  const supabase = client();
  const { data, error } = await supabase
    .from("kv_store_e3557d40")
    .select("value")
    .eq("key", key)
    .maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return (data?.value as T | undefined) ?? null;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client();
  const { error } = await supabase.from("kv_store_e3557d40").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async <T extends JsonValue>(
  entriesOrKeys: KVEntry<T>[] | string[],
  values?: T[],
): Promise<void> => {
  const supabase = client();
  const rows =
    typeof entriesOrKeys[0] === "string"
      ? (entriesOrKeys as string[]).map((k, i) => ({ key: k, value: values?.[i] }))
      : (entriesOrKeys as KVEntry<T>[]);
  const { error } = await supabase.from("kv_store_e3557d40").upsert(rows);
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async <T extends JsonValue>(keys: string[]): Promise<T[]> => {
  const supabase = client();
  const { data, error } = await supabase.from("kv_store_e3557d40").select("value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value as T) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client();
  const { error } = await supabase.from("kv_store_e3557d40").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async <T extends JsonValue>(prefix: string): Promise<T[]> => {
  const supabase = client();
  const { data, error } = await supabase
    .from("kv_store_e3557d40")
    .select("key, value")
    .like("key", prefix + "%");
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value as T) ?? [];
};
