apply plugin: "com.android.test"
apply plugin: "org.jetbrains.kotlin.android"

android {
    namespace "com.ogrencisosyalagi.macrobenchmark"
    compileSdk rootProject.ext.compileSdkVersion
    targetProjectPath = ":app"

    defaultConfig {
        minSdk 28
        targetSdk rootProject.ext.targetSdkVersion
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        benchmark {
            debuggable true
            matchingFallbacks = ["release"]
        }
    }

    experimentalProperties["android.experimental.self-instrumenting"] = true
}

dependencies {
    implementation "androidx.test.ext:junit:1.2.1"
    implementation "androidx.test:runner:1.6.2"
    implementation "androidx.test.uiautomator:uiautomator:2.3.0"
    implementation "androidx.benchmark:benchmark-macro-junit4:1.3.3"
}
