/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "kfvdbfoufybltybsxlhh";
export const publicAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmdmRiZm91ZnlibHR5YnN4bGhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY3OTE2NTEsImV4cCI6MjA5MjM2NzY1MX0.1irNWggWVOg89-cfI67Hpg5JV4MZvY0jQoMsOoxmkEg";
