const CATEGORY_OPTIONS = [
  "Genel",
  "Akademik Gelisim",
  "Arastirma",
  "Bilim",
  "Matematik",
  "Fizik",
  "Kimya",
  "Biyoloji",
  "Molekuler Biyoloji",
  "Biyoteknoloji",
  "Biyoinformatik",
  "Sinirbilim",
  "Jeoloji",
  "Cevre",
  "Iklim Krizi",
  "Sifir Atik",
  "Enerji",
  "Yenilenebilir Enerji",
  "Akilli Sehirler",
  "Tarim",
  "Gida",
  "Beslenme",
  "Saglik",
  "Tip",
  "Tip Teknolojileri",
  "Dis Hekimligi",
  "Eczacilik",
  "Hemsirelik",
  "Veterinerlik",
  "Psikoloji",
  "Toplum Sagligi",
  "Acil Yardim",
  "Afet Yönetimi",
  "Arama Kurtarma",
  "Yazilim",
  "Algoritma",
  "Açık Kaynak",
  "Web Gelistirme",
  "Mobil Gelistirme",
  "Oyun Gelistirme",
  "Oyun Tasarimi",
  "Sistem Tasarimi",
  "Bulut Bilisim",
  "Bulut Mimarisi",
  "DevOps",
  "Siber Güvenlik",
  "Veri Bilimi",
  "Veri Görselle?tirme",
  "Istatistik",
  "Yapay Zeka",
  "Makine ??renmesi",
  "Derin ??renme",
  "Uretken Yapay Zeka",
  "Robotik",
  "Robotik Kodlama",
  "Mikrodenetleyici",
  "Gomulu Sistemler",
  "Nesnelerin Interneti",
  "Elektrik Muhendisligi",
  "Elektronik",
  "Mekanik",
  "Endustri Muhendisligi",
  "Insaat Muhendisligi",
  "Mimarlik",
  "Ic Mimarlik",
  "Urun Tasarimi",
  "Urun Yönetimi",
  "UX UI Tasarim",
  "Grafik Tasarim",
  "3D Tasarim",
  "Animasyon",
  "Video Uretimi",
  "Montaj",
  "Dijital Sanat",
  "Fotoğraf",
  "Kisa Film",
  "Belgesel",
  "Sinema",
  "Tiyatro",
  "Muzik",
  "Muzik Teknolojileri",
  "Sahne Sanatlari",
  "Sahne ve Isik",
  "Orkestra",
  "Koro",
  "Dans",
  "Edebiyat",
  "Siir",
  "Kitap",
  "Yaratici Yazarlik",
  "Podcast",
  "Medya",
  "Gazetecilik",
  "?leti?im",
  "Sosyal Medya",
  "İçerik Uretimi",
  "Dijital Pazarlama",
  "Pazarlama",
  "Reklamcilik",
  "Halkla Iliskiler",
  "Marka Yönetimi",
  "Ekonomi",
  "Finans",
  "Finansal Okuryazarlik",
  "Fintech",
  "Kripto",
  "Borsa",
  "Yatirim",
  "Girişimcilik",
  "Startup",
  "SaaS",
  "Girişim Ekosistemi",
  "Girişim Sermayesi",
  "Inovasyon",
  "Proje Yönetimi",
  "Liderlik",
  "Mentorluk",
  "Kariyer",
  "Kariyer Planlama",
  "Staj",
  "Mulakat",
  "CV Hazirlama",
  "Portfolyo",
  "Sunum Teknikleri",
  "Topluluk Yönetimi",
  "Topluluk Etkinligi",
  "Sosyal Sorumluluk",
  "Gonulluluk",
  "Sivil Toplum",
  "Etik",
  "Hukuk",
  "Bilisim Hukuku",
  "Siyaset Bilimi",
  "Politika",
  "Uluslararasi Iliskiler",
  "Uluslararasi Ticaret",
  "Kamu Yönetimi",
  "MUN",
  "Model United Nations",
  "Erasmus",
  "Uluslararasi Programlar",
  "Turizm",
  "Kampus Yasami",
  "Sehir Kulturu",
  "Kultur Gezi",
  "Seyahat",
  "Spor",
  "Fitness",
  "Yoga",
  "Meditasyon",
  "Kosu",
  "Bisiklet",
  "Yuzme",
  "Tenis",
  "Futbol",
  "Voleybol",
  "Doga Sporlari",
  "Dagcilik",
  "Kamp",
  "Espor",
  "Kahve",
  "Yemek",
  "Moda",
  "Hayvan Haklari",
  "Farkindalik",
  "Toplumsal Cinsiyet",
  "Kisisel Gelisim",
  "Zaman Yönetimi",
  "Egitim",
  "Ogretmenlik",
  "Rehberlik",
  "Özel Egitim",
  "Yabanci Dil",
  "Ingilizce",
  "Almanca",
  "Fransizca",
  "Ispanyolca",
  "Italyanca",
  "Arapca",
  "Japonca",
  "Korece",
  "Cince",
  "Turkce",
  "IEEE",
  "ACM",
  "Diğer",
] as const;

const sortTrUnique = (items: readonly string[]) =>
  Array.from(new Set(items)).sort((a, b) => a.localeCompare(b, "tr", { sensitivity: "base" }));

export const categories = sortTrUnique(CATEGORY_OPTIONS);
