import { categories as categoryOptions } from "./categories";
import {
  universities as universityOptions,
  departments as departmentOptions,
  gradeYears as gradeYearOptions,
  clubCategories as clubCategoryOptions,
  interests as interestOptions,
} from "./universities";

const sortTrUnique = (items: readonly string[]) =>
  Array.from(new Set(items)).sort((a, b) => a.localeCompare(b, "tr", { sensitivity: "base" }));

export const eventTypes = sortTrUnique([
  "Seminer",
  "Atolye",
  "Konferans",
  "Panel",
  "Soylesi",
  "Egitim",
  "Masterclass",
  "Webinar",
  "Canli Yayin",
  "Bootcamp",
  "Hackathon",
  "Ideathon",
  "Datathon",
  "Game Jam",
  "Build Day",
  "Hack Day",
  "Kodlama Gecesi",
  "Laboratuvar Calismasi",
  "Uygulamali Ders",
  "Teknik Inceleme",
  "Teknik Gezi",
  "Saha Calismasi",
  "Yarisma",
  "Vaka Yarismasi",
  "Bilgi Yarismasi",
  "Quiz Gecesi",
  "Turnuva",
  "Espor Turnuvasi",
  "Satranc Turnuvasi",
  "Lig Maci",
  "Dostluk Maci",
  "Spor Etkinligi",
  "Antrenman",
  "Kosu Etkinligi",
  "Bisiklet Turu",
  "Doga Yuruyusu",
  "Yoga Etkinligi",
  "Kamp",
  "Gezi",
  "Topluluk Bulusmasi",
  "Topluluk Gunu",
  "Tanisma Etkinligi",
  "Meetup",
  "Networking",
  "Speed Networking",
  "Kampus Senligi",
  "Festival",
  "Fuar",
  "Kurultay",
  "Calistay",
  "Kariyer Gunu",
  "Kariyer Fuari",
  "Staj Bulusmasi",
  "Mulakat Simulasyonu",
  "CV Atolyesi",
  "Portfolyo Incelemesi",
  "Case Study",
  "Mentorluk Programi",
  "Kocluk Oturumu",
  "Ofis Saati",
  "Soru Cevap",
  "Demo Day",
  "Pitching",
  "Urun Lansmani",
  "Proje Sunumu",
  "Prototip Gunu",
  "Açık Mikrofon",
  "Konser",
  "Sergi",
  "Film Gösterimi",
  "Tiyatro Gösterimi",
  "Sahne Performansi",
  "Dinleti",
  "Standup",
  "DJ Performansi",
  "Podcast Kaydi",
  "Kitap Tartismasi",
  "Okulübüma Kulübü",
  "Deneyim Paylaşımı",
  "Kulüp Toplantisi",
  "Yönetim Kurulu Toplantisi",
  "Komite Toplantisi",
  "Genel Kurul",
  "Sosyal Sorumluluk",
  "Gonulluluk",
  "Bagis Kampanyasi",
  "Farkindalik Etkinligi",
  "Sosyal Etki Projesi",
  "Is Birligi Bulusmasi",
  "Mezun Bulusmasi",
  "Toplanti",
  "Calisma Oturumu",
  "Rehberlik Oturumu",
  "Acilis Etkinligi",
  "Kapanis Etkinligi",
  "Diğer",
]);

export const categories = categoryOptions;
export const universities = universityOptions;
export const departments = departmentOptions;
export const gradeYears = gradeYearOptions;
export const clubCategories = clubCategoryOptions;
export const interests = interestOptions;
