export const DEPARTMENT_OPTIONS_EXTRA = [
  "Kaynak Teknolojisi",
  "Kenevir Dokulübüma Tezgahtarlığı",
  "Kentsel Tasarım Ve Peyzaj Mimarlığı",
  "Kimya",
  "Kimya Mühendisliği",
  "Kimya Öğretmenliği",
  "Kimya Teknolojisi",
  "Kimya-Biyoloji Mühendisliği",
  "Klasik Arkeoloji",
  "Kontrol Ve Otomasyon Mühendisliği",
  "Kontrol Ve Otomasyon Teknolojisi",
  "Kooperatifçilik",
  "Kore Dili Ve Edebiyatı",
  "Kozmetik Teknolojisi",
  "Kurgu, Ses Ve Görüntü Yönetimi",
  "Kuyumculuk Ve Mücevher Tasarımı",
  "Kuyumculuk Ve Takı Tasarımı",
  "Kültür Varlıklarını Koruma Ve Onarım",
  "Kültür Ve İletişim Bilimleri",
  "Kültürel Miras Ve Turizm",
  "Kümes Hayvanları Yetiştiriciliği",
  "Küresel Siyaset Ve Uluslararası İlişkiler",
  "Kürt Dili Ve Edebiyatı",
  "Laborant Ve Veteriner Sağlık",
  "Laboratuvar Teknolojisi",
  "Latin Dili Ve Edebiyatı",
  "Leh Dili Ve Edebiyatı",
  "Lojistik",
  "Lojistik Yönetimi",
  "Maden Mühendisliği",
  "Madencilik Teknolojisi",
  "Makine",
  "Makine Mühendisliği",
  "Makine Resim Ve Konstrüksiyonu",
  "Maliye",
  "Maliye (Önlisans)",
  "Malzeme Bilimi Ve Mühendisliği",
  "Malzeme Bilimi Ve Nanoteknoloji Mühendisliği",
  "Malzeme Bilimi Ve Teknolojileri",
  "Mantarcılık",
  "Marina Ve Yat İşletmeciliği",
  "Marka İletişimi",
  "Matematik",
  "Matematik Mühendisliği",
  "Matematik Öğretmenliği",
  "Matematik Ve Bilgisayar Bilimleri",
  "Medya Ve Görsel Sanatlar",
  "Medya Ve İletişim",
  "Medya Ve İletişim (Önlisans)",
  "Mekatronik",
  "Mekatronik Mühendisliği",
  "Menkul Kıymetler Ve Sermaye Piyasası",
  "Mermer Teknolojisi",
  "Metalurji",
  "Metalurji Ve Malzeme Mühendisliği",
  "Meteoroloji Mühendisliği",
  "Meyve Ve Sebze İşleme Teknolojisi",
  "Mimari Dekoratif Sanatlar",
  "Mimari Restorasyon",
  "Mimarlık",
  "Mobil Teknolojileri",
  "Mobilya Ve Dekorasyon",
  "Moda Tasarımı",
  "Moda Tasarımı (Önlisans)",
  "Moda Yönetimi",
  "Moleküler Biyoloji Ve Genetik",
  "Moleküler Biyoteknoloji",
  "Muhasebe Ve Finans Yönetimi",
  "Muhasebe Ve Vergi Uygulamaları",
  "Mühendislik Programları",
  "Mühendislik Ve Doğa Bilimleri Programları",
  "Mütercim-Tercümanlık",
  "Müzecilik",
  "Nanobilim Ve Nanoteknoloji",
  "Nanoteknoloji Mühendisliği",
  "Nüfus Ve Vatandaşlık",
  "Nükleer Enerji Mühendisliği",
  "Nükleer Teknoloji Ve Radyasyon Güvenliği",
  "Nükleer Tıp Teknikleri",
  "Odyoloji",
  "Odyometri",
  "Okul Öncesi Öğretmenliği",
  "Optik Ve Akustik Mühendisliği",
  "Optisyenlik",
  "Organik Tarım",
  "Organik Tarım İşletmeciliği",
  "Orman Endüstrisi Mühendisliği",
  "Orman Mühendisliği",
  "Ormancılık Ve Orman Ürünleri",
  "Ortez Ve Protez",
  "Ortopedik Protez Ve Ortez",
  "Otel Yöneticiliği",
  "Otobüs Kaptanlığı",
  "Otomotiv Gövde Ve Yüzey İşlem Teknolojileri",
  "Otomotiv Mühendisliği",
  "Otomotiv Teknolojisi",
  "Otopsi Yardımcılığı",
  "Özel Eğitim Öğretmenliği",
  "Özel Güvenlik Ve Koruma",
  "Pastacılık Ve Ekmekçilik",
  "Patoloji Laboratuvar Teknikleri",
  "Pazarlama",
  "Pazarlama (Önlisans)",
  "Perakende Satış Ve Mağaza Yönetimi",
  "Perfüzyon",
  "Petrol Ve Doğalgaz Mühendisliği",
  "Peyzaj Mimarlığı",
  "Peyzaj Ve Süs Bitkileri Yetiştiriciliği",
  "Pilotaj",
  "Podoloji",
  "Polimer Malzeme Mühendisliği",
  "Polimer Teknolojisi",
  "Politika Ve Ekonomi",
  "Posta Hizmetleri",
  "Protohistorya Ve Ön Asya Arkeolojisi",
  "Psikoloji",
  "Psikolojik Danışmanlık Ve Rehberlik",
  "Psikolojik Danışmanlık Ve Rehberlik Öğretmenliği",
  "Radyo Ve Televizyon Programcılığı",
  "Radyo Ve Televizyon Teknolojisi",
  "Radyo, Televizyon Ve Sinema",
  "Radyoterapi",
  "Rafineri Ve Petro-Kimya Teknolojisi",
  "Raylı Sistemler Elektrik Ve Elektronik",
  "Raylı Sistemler İşletmeciliği",
  "Raylı Sistemler Makine Teknolojisi",
  "Raylı Sistemler Makinistliği",
  "Raylı Sistemler Mühendisliği",
  "Raylı Sistemler Yol Teknolojisi",
  "Rehberlik Ve Psikolojik Danışmanlık",
  "Reklam Tasarımı Ve İletişimi",
  "Reklamcılık",
  "Reklamcılık (Önlisans)",
  "Rekreasyon",
  "Rekreasyon Yönetimi",
  "Rus Dili Ve Edebiyatı",
  "Rus Dili Ve Edebiyatı Öğretmenliği",
  "Rusça Mütercim Ve Tercümanlık",
  "Saç Bakımı Ve Güzellik Hizmetleri",
  "Sağlık Bilgi Sistemleri Teknikerliği",
  "Sağlık Kurumları İşletmeciliği",
  "Sağlık Turizmi İşletmeciliği",
  "Sağlık Yönetimi",
  "Sahne Işık Ve Ses Teknolojileri",
  "Sahne Ve Dekor Tasarımı",
  "Sanal Ve Artırılmış Gerçeklik",
  "Sanat Tarihi",
  "Sanat Ve Kültür Yönetimi",
  "Sanat Ve Sosyal Bilimler Programları",
  "Seracılık",
  "Seramik Ve Cam Tasarımı",
  "Sermaye Piyasası",
  "Seyahat İşletmeciliği",
  "Seyahat İşletmeciliği Ve Turizm Rehberliği",
  "Sınıf Öğretmenliği",
  "Siber Güvenlik",
  "Siber Güvenlik Analistliği Ve Operatörlüğü",
  "Sigortacılık",
  "Sigortacılık Ve Aktüerya Bilimleri",
  "Sigortacılık Ve Risk Yönetimi",
  "Sigortacılık Ve Sosyal Güvenlik",
  "Silah Sanayi Teknikerliği",
  "Sinema Ve Dijital Medya",
  "Sinema Ve Televizyon",
  "Sinoloji",
  "Sivil Hava Ulaştırma İşletmeciliği",
  "Sivil Havacılık Kabin Hizmetleri",
  "Sivil Savunma Ve İtfaiyecilik",
  "Siyasal Bilimler",
  "Siyaset Bilimi",
  "Siyaset Bilimi Ve Kamu Yönetimi",
  "Siyaset Bilimi Ve Uluslararası İlişkiler",
  "Sondaj Teknolojisi",
  "Sosyal Bilgiler Öğretmenliği",
  "Sosyal Güvenlik",
  "Sosyal Hizmet",
  "Sosyal Hizmetler",
  "Sosyal Medya Yöneticiliği",
  "Sosyoloji",
  "Spor Yöneticiliği",
  "Spor Yönetimi",
  "Su Altı Teknolojisi",
  "Su Bilimleri Ve Mühendisliği",
  "Su Ürünleri İşleme Teknolojisi",
  "Su Ürünleri Mühendisliği",
  "Sulama Teknolojisi",
  "Sümeroloji",
  "Süryani Dili Ve Edebiyatı",
  "Süt Teknolojisi",
  "Süt Ve Besi Hayvancılığı",
  "Süt Ve Ürünleri Teknolojisi",
  "Şarap Üretim Teknolojisi",
  "Şehir Ve Bölge Planlama",
  "Tahribatsız Muayene",
  "Takı Tasarımı",
  "Takı Tasarımı Ve İmalatı",
  "Tapu Kadastro",
  "Tapu Ve Kadastro",
  "Tarım Ekonomisi",
  "Tarım Makineleri",
  "Tarım Makineleri Ve Teknolojileri Mühendisliği",
  "Tarım Teknolojisi",
  "Tarım Ticareti Ve İşletmeciliği",
  "Tarımsal Biyoteknoloji",
  "Tarımsal Genetik Mühendisliği",
  "Tarımsal İşletmecilik",
  "Tarımsal Yapılar Ve Sulama",
  "Tarih",
  "Tarih Öğretmenliği",
  "Tarih Öncesi Arkeolojisi",
  "Tarla Bitkileri",
  "Tarla Bitkileri (Önlisans)",
  "Teknoloji Ve Bilgi Yönetimi",
  "Tekstil Mühendisliği",
  "Tekstil Tasarımı",
  "Tekstil Teknolojisi",
  "Tekstil Ve Halı Makineleri",
  "Tekstil Ve Moda Tasarımı",
  "Televizyon Haberciliği Ve Programcılığı",
  "Tıbbi Dokümantasyon Ve Sekreterlik",
  "Tıbbi Görüntüleme Teknikleri",
  "Tıbbi Laboratuvar Teknikleri",
  "Tıbbi Tanıtım Ve Pazarlama",
  "Tıbbi Ve Aromatik Bitkiler",
  "Tıp",
  "Tıp Mühendisliği",
  "Tiyatro Eleştirmenliği Ve Dramaturji",
  "Tohum Bilimi Ve Teknolojisi",
  "Tohumculuk Teknolojisi",
  "Toprak Bilimi Ve Bitki Besleme",
  "Turist Rehberliği",
  "Turizm Animasyonu",
  "Turizm İşletmeciliği",
  "Turizm Rehberliği",
  "Turizm Ve Otel İşletmeciliği",
  "Turizm Ve Otel İşletmeciliği (Önlisans)",
  "Turizm Ve Seyahat Hizmetleri",
  "Türk Dili Ve Edebiyatı",
  "Türk Dili Ve Edebiyatı Öğretmenliği",
  "Türk Halkbilimi",
  "Türk İslam Arkeolojisi",
  "Türkçe Öğretmenliği",
  "Türkoloji",
  "Tütün Eksperliği",
  "Uçak Bakım Ve Onarım",
  "Uçak Elektrik Ve Elektroniği",
  "Uçak Gövde Ve Motor Bakımı",
  "Uçak Mühendisliği",
  "Uçak Teknolojisi",
  "Uçuş Harekat Yöneticiliği",
  "Ukrayna Dili Ve Edebiyatı",
  "Ulaştırma Ve Trafik Hizmetleri",
  "Uluslararası Ekonomi",
  "Uluslararası Finans",
  "Uluslararası Finans Ve Bankacılık",
  "Uluslararası Girişimcilik",
  "Uluslararası İlişkiler",
  "Uluslararası İşletme Yönetimi",
  "Uluslararası Ticaret",
  "Uluslararası Ticaret Ve Finans",
  "Uluslararası Ticaret Ve İşletmecilik",
  "Uluslararası Ticaret Ve Lojistik",
  "Un Ve Unlu Mamuller Teknolojisi",
  "Urdu Dili Ve Edebiyatı",
  "Uygulamalı İngilizce Çevirmenlik",
  "Uygulamalı İspanyolca Çevirmenlik",
  "Uzay Bilimleri Ve Teknolojileri",
  "Uzay Mühendisliği",
  "Uzay Ve Uydu Mühendisliği",
  "Üretimde Kalite Kontrol",
  "Veterinerlik",
  "Web Tasarımı Ve Kodlama",
  "Yaban Hayatı Ekolojisi Ve Yönetimi",
  "Yağ Endüstrisi",
  "Yapay Zeka Mühendisliği",
  "Yapay Zekâ Operatörlüğü",
  "Yapay Zeka Ve Veri Mühendisliği",
  "Yapı Denetimi",
  "Yapı Ressamlığı",
  "Yapı Tesisat Teknolojisi",
  "Yapı Yalıtım Teknolojisi",
  "Yaşlı Bakımı",
  "Yat Kaptanlığı",
  "Yazılım Geliştirme",
  "Yazılım Mühendisliği",
  "Yeni Medya",
  "Yeni Medya Ve Gazetecilik",
  "Yeni Medya Ve İletişim",
  "Yerel Yönetimler",
  "Yerel Yönetimler (Önlisans)",
  "Yiyecek Ve İçecek İşletmeciliği",
  "Yönetim Bilimleri Programları",
  "Yönetim Bilişim Sistemleri",
  "Yunan Dili Ve Edebiyatı",
  "Zaza Dili Ve Edebiyatı",
  "Zeytincilik Ve Zeytin İşleme Teknolojisi",
  "Ziraat Mühendisliği Programları",
  "Zootekni",
] as const;
