import { DEPARTMENT_OPTIONS_EXTRA } from "./universities.departments.extra";

const DEPARTMENT_OPTIONS_PRIMARY = [
  "Acil Durum Ve Afet Yönetimi",
  "Acil Yardım Ve Afet Yönetimi",
  "Açık Deniz Sondaj Teknolojisi",
  "Açık Deniz Tabanı Uygulamaları Teknolojisi",
  "Adalet",
  "Adli Bilimler",
  "Adli Bilişim Mühendisliği",
  "Ağaç İşleri Endüstri Mühendisliği",
  "Ağız ve Diş Sağlığı",
  "Aile Ve Tüketici Bilimleri",
  "Aktüerya Bilimleri",
  "Alman Dili Ve Edebiyatı",
  "Almanca Mütercim Ve Tercümanlık",
  "Almanca Öğretmenliği",
  "Alternatif Enerji Kaynakları Teknolojisi",
  "Ambalaj Tasarımı",
  "Ameliyathane Hizmetleri",
  "Amerikan Kültürü Ve Edebiyatı",
  "Anestezi",
  "Antrenörlük Eğitimi",
  "Antropoloji",
  "Arap Dili Ve Edebiyatı",
  "Arapça Mütercim Ve Tercümanlık",
  "Arapça Öğretmenliği",
  "Arıcılık",
  "Arkeoloji",
  "Arkeoloji Ve Sanat Tarihi",
  "Arnavut Dili Ve Edebiyatı",
  "Astronomi Ve Uzay Bilimleri",
  "Aşçılık",
  "Atçılık Ve Antrenörlüğü",
  "Atık Yönetimi",
  "Avcılık Ve Yaban Hayatı",
  "Ayakkabı Tasarım Ve Üretimi",
  "Ayakkabı Tasarımı Ve Üretimi",
  "Azerbaycan Türkçesi Ve Edebiyatı",
  "Bağcılık",
  "Bağcılık Ve Bağ Ürünleri Teknolojisi",
  "Bahçe Bitkileri",
  "Bahçe Tarımı",
  "Balıkçılık Teknolojisi Mühendisliği",
  "Bankacılık",
  "Bankacılık Ve Finans",
  "Bankacılık Ve Sigortacılık",
  "Bankacılık Ve Sigortacılık (Önlisans)",
  "Basım Teknolojileri",
  "Basım Ve Yayım Teknolojileri",
  "Basın Ve Yayın",
  "Batı Dilleri",
  "Beden Eğitimi Ve Spor Öğretmenliği",
  "Beslenme Ve Diyetetik",
  "Bıçakçılık Ve El Aletleri Üretim Teknolojisi",
  "Bilgi Güvenliği Teknolojisi",
  "Bilgi Ve Belge Yönetimi",
  "Bilgi Yönetimi",
  "Bilgisayar Bilimleri",
  "Bilgisayar Destekli Tasarım Ve Animasyon",
  "Bilgisayar Mühendisliği",
  "Bilgisayar Operatörlüğü",
  "Bilgisayar Programcılığı",
  "Bilgisayar Teknolojisi",
  "Bilgisayar Teknolojisi Ve Bilişim Sistemleri",
  "Bilgisayar Ve Öğretim Teknolojileri Öğretmenliği",
  "Bilim Tarihi",
  "Bilişim Güvenliği Teknolojisi",
  "Bilişim Sistemleri Mühendisliği",
  "Bilişim Sistemleri Ve Teknolojileri",
  "Bitki Koruma",
  "Bitki Koruma (Önlisans)",
  "Bitkisel Üretim Ve Teknolojileri",
  "Biyokimya",
  "Biyokimya (Önlisans)",
  "Biyoloji",
  "Biyoloji Öğretmenliği",
  "Biyomedikal Cihaz Teknolojisi",
  "Biyomedikal Mühendisliği",
  "Biyomühendislik",
  "Biyosistem Mühendisliği",
  "Biyoteknoloji",
  "Boşnak Dili Ve Edebiyatı",
  "Boya Teknolojisi",
  "Bulgar Dili Ve Edebiyatı",
  "Bulgarca Mütercim Ve Tercümanlık",
  "Büro Yönetimi Ve Yönetici Asistanlığı",
  "Cevher Hazırlama Mühendisliği",
  "Ceza İnfaz Ve Güvenlik Hizmetleri",
  "Cnc Programlama Ve Operatörlüğü",
  "Coğrafi Bilgi Sistemleri",
  "Coğrafya",
  "Coğrafya Öğretmenliği",
  "Çağdaş Türk Lehçeleri Ve Edebiyatları",
  "Çağdaş Yunan Dili Ve Edebiyatı",
  "Çağrı Merkezi Hizmetleri",
  "Çalışma Ekonomisi Ve Endüstri İlişkileri",
  "Çay Tarımı Ve İşleme Teknolojisi",
  "Çerkez Dili Ve Kültürü",
  "Çeviribilimi",
  "Çevre Koruma Ve Kontrol",
  "Çevre Mühendisliği",
  "Çevre Sağlığı",
  "Çevre Temizliği Ve Denetimi",
  "Çim Alan Tesisi Ve Yönetimi",
  "Çin Dili Ve Edebiyatı",
  "Çince Mütercim Ve Tercümanlık",
  "Çini Sanatı Ve Tasarımı",
  "Çizgi Film Ve Animasyon",
  "Çocuk Gelişimi",
  "Çocuk Gelişimi (Önlisans)",
  "Çocuk Koruma Ve Bakım Hizmetleri",
  "Çok Boyutlu Modelleme Ve Animasyon",
  "Deniz Brokerliği",
  "Deniz Ulaştırma İşletme Mühendisliği",
  "Deniz Ulaştırma Ve İşletme",
  "Deniz Ve Liman İşletmeciliği",
  "Denizcilik İşletmeleri Yönetimi",
  "Deri Mühendisliği",
  "Deri Teknolojisi",
  "Dezenfeksiyon, Sterilizasyon Ve Antisepsi Teknikerliği",
  "Dış Ticaret",
  "Dijital Fabrika Teknolojileri",
  "Dijital Oyun Tasarımı",
  "Dil Ve Konuşma Terapisi",
  "Dilbilimi",
  "Diş Hekimliği",
  "Diş Protez Teknolojisi",
  "Diyaliz",
  "Doğal Yapı Taşları Teknolojisi",
  "Doğalgaz Ve Tesisatı Teknolojisi",
  "Doğu Dilleri",
  "Döküm",
  "Ebelik",
  "Eczacılık",
  "Eczane Hizmetleri",
  "Egzersiz Ve Spor Bilimleri",
  "Ekonometri",
  "Ekonomi",
  "Ekonomi Ve Finans",
  "El Sanatları",
  "Elektrik",
  "Elektrik Enerjisi Üretim, İletim Ve Dağıtımı",
  "Elektrik Mühendisliği",
  "Elektrik-Elektronik Mühendisliği",
  "Elektrikli Cihaz Teknolojisi",
  "Elektronik Haberleşme Teknolojisi",
  "Elektronik Mühendisliği",
  "Elektronik Teknolojisi",
  "Elektronik Ticaret Ve Yönetimi",
  "Elektronik Ve Haberleşme Mühendisliği",
  "Elektronörofizyoloji",
  "Emlak Ve Emlak Yönetimi",
  "Emlak Yönetimi",
  "Endüstri Mühendisliği",
  "Endüstri Ürünleri Tasarımı",
  "Endüstriyel Cam Ve Seramik",
  "Endüstriyel Hammaddeler İşleme Teknolojisi",
  "Endüstriyel Kalıpçılık",
  "Endüstriyel Tasarım",
  "Endüstriyel Tasarım Mühendisliği",
  "Enerji Bilimi Ve Teknolojileri",
  "Enerji Sistemleri Mühendisliği",
  "Enerji Tesisleri İşletmeciliği",
  "Enerji Yönetimi",
  "Engelli Bakımı Ve Rehabilitasyon",
  "Engelliler İçin Gölge Öğreticilik",
  "Ergoterapi",
  "Ermeni Dili Ve Kültürü",
  "Eser Koruma",
  "Eski Yunan Dili Ve Edebiyatı",
  "Et Ve Ürünleri Teknolojisi",
  "E-Ticaret Ve Pazarlama",
  "Ev İdaresi",
  "Evde Hasta Bakımı",
  "Fars Dili Ve Edebiyatı",
  "Farsça Mütercim Ve Tercümanlık",
  "Felsefe",
  "Felsefe Grubu Öğretmenliği",
  "Fen Bilgisi Öğretmenliği",
  "Fındık Eksperliği",
  "Fidan Yetiştiriciliği",
  "Film Tasarımı Ve Yazarlığı",
  "Film Tasarımı Ve Yönetimi",
  "Film Tasarımı Ve Yönetmenliği",
  "Finans Ve Bankacılık",
  "Fizik",
  "Fizik Mühendisliği",
  "Fizik Öğretmenliği",
  "Fizyoterapi",
  "Fizyoterapi Ve Rehabilitasyon",
  "Fotoğraf",
  "Fotoğraf Ve Video",
  "Fotoğrafçılık Ve Kameramanlık",
  "Fotonik",
  "Fransız Dili Ve Edebiyatı",
  "Fransızca Mütercim Ve Tercümanlık",
  "Fransızca Öğretmenliği",
  "Gastronomi Ve Mutfak Sanatları",
  "Gayrimenkul Geliştirme Ve Yönetimi",
  "Gazetecilik",
  "Geleneksel El Sanatları",
  "Geleneksel Tekstillerin Korunması Ve Restorasyonu",
  "Geleneksel Türk Sanatları",
  "Gemi İnşaatı",
  "Gemi İnşaatı Ve Gemi Makineleri Mühendisliği",
  "Gemi Makineleri İşletme Mühendisliği",
  "Gemi Makineleri İşletmeciliği",
  "Gemi Ve Deniz Teknolojisi Mühendisliği",
  "Gemi Ve Yat Tasarımı",
  "Genetik Ve Biyomühendislik",
  "Geomatik Mühendisliği",
  "Geoteknik",
  "Gerontoloji",
  "Gıda Kalite Kontrolü Ve Analizi",
  "Gıda Mühendisliği",
  "Gıda Teknolojisi",
  "Gıda Teknolojisi (Önlisans)",
  "Girişimcilik",
  "Giyim Üretim Teknolojisi",
  "Görsel İletişim",
  "Görsel İletişim Tasarımı",
  "Görsel Sanatlar",
  "Görsel Sanatlar Ve İletişim Tasarımı",
  "Grafik",
  "Grafik Sanatlar",
  "Grafik Tasarımı",
  "Grafik Tasarımı (Önlisans)",
  "Gümrük İşletme",
  "Gürcü Dili Ve Edebiyatı",
  "Halıcılık Ve Kilimcilik",
  "Halkbilimi",
  "Halkla İlişkiler Ve Reklamcılık",
  "Halkla İlişkiler Ve Tanıtım",
  "Halkla İlişkiler Ve Tanıtım (Önlisans)",
  "Harita Mühendisliği",
  "Harita Ve Kadastro",
  "Hasta Bakımı",
  "Hava Lojistiği",
  "Havacılık Elektrik Ve Elektroniği",
  "Havacılık Ve Uzay Mühendisliği",
  "Havacılık Yönetimi",
  "Hayvansal Üretim Ve Teknolojileri",
  "Hemşirelik",
  "Hibrid Ve Elektrikli Taşıtlar Teknolojisi",
  "Hidrojeoloji Mühendisliği",
  "Hindoloji",
  "Hititoloji",
  "Hukuk",
  "Hukuk Büro Yönetimi Ve Sekreterliği",
  "Hungaroloji",
  "İbrani Dili Ve Kültürü",
  "İç Mekan Tasarımı",
  "İç Mimarlık",
  "İç Mimarlık Ve Çevre Tasarımı",
  "İklimlendirme Ve Soğutma Teknolojisi",
  "İkram Hizmetleri",
  "İktisadi Ve İdari Bilimler Programları",
  "İktisat",
  "İlahiyat",
  "İlahiyat (Önlisans)",
  "İletişim",
  "İletişim Bilimleri",
  "İletişim Sanatları",
  "İletişim Tasarımı Ve Yönetimi",
  "İletişim Ve Tasarımı",
  "İlk Ve Acil Yardım",
  "İlköğretim Matematik Öğretmenliği",
  "İmalat Mühendisliği",
  "İngiliz Dilbilimi",
  "İngiliz Dili Ve Edebiyatı",
  "İngilizce Mütercim Ve Tercümanlık",
  "İngilizce Öğretmenliği",
  "İngilizce, Fransızca Mütercim Ve Tercümanlık",
  "İnsan Kaynakları Yönetimi",
  "İnsan Kaynakları Yönetimi (Önlisans)",
  "İnsansız Hava Aracı Teknolojisi Ve Operatörlüğü",
  "İnşaat Mühendisliği",
  "İnşaat Teknolojisi",
  "İnternet Ve Ağ Teknolojileri",
  "İslam Bilimleri",
  "İslam İktisadı Ve Finans",
  "İslami İlimler",
  "İslami İlimler (Önlisans)",
  "İspanyol Dili Ve Edebiyatı",
  "İstatistik",
  "İstatistik Ve Bilgisayar Bilimleri",
  "İş Makineleri Operatörlüğü",
  "İş Sağlığı Ve Güvenliği",
  "İş Sağlığı Ve Güvenliği (Önlisans)",
  "İş Ve Uğraşı Terapisi",
  "İşletme",
  "İşletme Mühendisliği",
  "İşletme Yönetimi",
  "İtalyan Dili Ve Edebiyatı",
  "Japon Dili Ve Edebiyatı",
  "Japonca Mütercim Ve Tercümanlık",
  "Japonca Öğretmenliği",
  "Jeofizik Mühendisliği",
  "Jeoloji Mühendisliği",
  "Kamu Yönetimi",
  "Kanatlı Hayvan Yetiştiriciliği",
  "Karşılaştırmalı Edebiyat",
] as const;

export const DEPARTMENT_OPTIONS = [
  ...DEPARTMENT_OPTIONS_PRIMARY,
  ...DEPARTMENT_OPTIONS_EXTRA,
] as const;
